Type = [
	"Car",
	"Motorcycle",
	"Other"
]

Other = [
	"Other"
]

CarStyle = [
    "Full custom","Classic", "Vintage", "Hot rod", "Rat rod"
]

MotorbikeStyle = [
    "Classic", "Custom", "Chopper", "Bobber", "Cafe Racer","Full custom", "Road Bike"
]

Car = [
    "Abarth",
    "AC",
    "Acura",
    "Aixam",
    "Alfa Romeo",
    "Alpina",
    "Artega",
    "Asia Motors",
    "Aston Martin",
    "Audi",
    "Austin",
    "Austin Healey",
    "Bentley",
    "BMW",
    "Borgward",
    "Brilliance",
    "Bugatti",
    "Buick",
    "Cadillac",
    "Casalini",
    "Caterham",
    "Chatenet",
    "Chevrolet",
    "Chrysler",
    "Citroën",
    "Cobra",
    "Corvette",
    "Dacia",
    "Daewoo",
    "Daihatsu",
    "DeTomaso",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Fisker",
    "Ford",
    "GAC Gonow",
    "Gemballa",
    "GMC",
    "Grecav",
    "Hamann",
    "Holden",
    "Honda",
    "Hummer",
    "Hyundai",
    "Infiniti",
    "Isuzu",
    "Iveco",
    "Jaguar",
    "Jeep",
    "Kia",
    "Königsegg",
    "KTM",
    "Lada",
    "Lamborghini",
    "Lancia",
    "Land Rover",
    "Landwind",
    "Lexus",
    "Ligier",
    "Lincoln",
    "Lotus",
    "Mahindra",
    "Maserati",
    "Maybach",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "MG",
    "Microcar",
    "MINI",
    "Mitsubishi",
    "Morgan",
    "Nissan",
    "NSU",
    "Oldsmobile",
    "Opel",
    "Pagani",
    "Peugeot",
    "Piaggio",
    "Plymouth",
    "Pontiac",
    "Porsche",
    "Proton",
    "Renault",
    "Rolls-Royce",
    "Rover",
    "Ruf",
    "Saab",
    "Santana",
    "Seat",
    "Skoda",
    "Smart",
    "speedART",
    "Spyker",
    "Ssangyong",
    "Subaru",
    "Suzuki",
    "Talbot",
    "Tata",
    "TECHART",
    "Tesla",
    "Toyota",
    "Trabant",
    "Triumph",
    "TVR",
    "Volkswagen",
    "Volvo",
    "Wartburg",
    "Westfield",
    "Wiesmann",
    "Other"
]

Motorcycle = [
    "Adly",
    "Aeon",
    "Aixam",
    "Aprilia",
    "Arctic Cat",
    "Baotian",
    "Barossa",
    "Bashan",
    "Beeline",
    "Benelli",
    "Beta",
    "Big Dog Motorcycles",
    "Bimota",
    "Blata",
    "BMW",
    "Bombardier",
    "Boom",
    "BRP",
    "BSA",
    "Buell",
    "Burelli",
    "Cagiva",
    "Can Am",
    "Cectek",
    "CFMOTO",
    "CPI",
    "Daelim",
    "Derbi",
    "Dinli",
    "DKW",
    "Ducati",
    "e-max",
    "emco",
    "E-Ton",
    "Explorer",
    "Gasgas",
    "Generic",
    "GG Motorradtechnik",
    "Gilera",
    "GOES",
    "Gorilla",
    "Harley-Davidson",
    "Hercules",
    "Herkules",
    "Honda",
    "Horex",
    "Husaberg",
    "Husqvarna",
    "Hyosung",
    "Indian",
    "Italjet",
    "Jawa",
    "Jinling",
    "Kawasaki",
    "Keeway",
    "Kimi",
    "Kingway",
    "Knievel",
    "Kreidler",
    "KTM",
    "Kumpan",
    "Kymco",
    "Lambretta",
    "Laverda",
    "Lifan",
    "Linhai",
    "LML",
    "Luxxon",
    "Maico",
    "Malaguti",
    "MBK",
    "Megelli",
    "Motobi",
    "Moto Guzzi",
    "Moto Morini",
    "Motowell",
    "MV Agusta",
    "Mz",
    "Norton",
    "NSU",
    "Online",
    "Pegasus",
    "Peugeot",
    "PGO",
    "Piaggio",
    "Polaris",
    "Puch",
    "Quadro",
    "Rewaco",
    "Rieju",
    "Rivero",
    "Royal Enfield",
    "Sachs",
    "Seikel",
    "Sherco",
    "Shineray",
    "Simson",
    "Skyteam",
    "SMC",
    "Suzuki",
    "SYM",
    "Tauris",
    "TGB",
    "TM",
    "Triton",
    "Triumph",
    "Ural",
    "Vespa",
    "VICTORY",
    "Voxan",
    "WMI",
    "Yamaha",
    "Zero",
    "Zhongyu",
    "Zündapp",
    "Other"
]